package dataStorageServer;

message storeRequest {
    optional int64 inputLong = 1;
    optional string fileName = 2;
}

message fetchRequest{
    optional int64 outputLong = 1;
    optional string fileName = 2;
}

message responseData{
    optional int32 errCode = 1;
}

service storeDataStorageService{
    rpc storeDataStorageServiceProcess (storeRequest) returns (responseData) {}
}

service fetchDataStorageService{
    rpc fetchDataStorageServiceProcess (fetchRequest) returns (responseData) {}
}