package dataStorageServer;

message storeRequest {
    repeated int64 inputLong = 1;
    optional string fileName = 2;
}

message fetchRequest{
    repeated int64 outputLong = 1;
    optional string fileName = 2;
}

message responseData{
    optional int32 errCode = 1;
}

message emptyMessage{

}

service storeDataStorageService{
    rpc storeDataStorageServiceProcess (storeRequest) returns (emptyMessage) {}
}

service fetchDataStorageService{
    rpc fetchDataStorageServiceProcess (fetchRequest) returns (emptyMessage) {}
}